### ISSUE TITLE
Image compositing crops images incorrectly when posting to Discord

### ISSUE THREAD

**Issue by MStrohmeier** [FixTweet/mosaic#4]
Steps to reproduce
1. Pick a tweet with two images on it.
2. Post it to Discord using any of the FixTweet domains
3. Images are cropped horizontally in the Discord preview.

For example, [this tweet](https://twitter.com/field_of_reeds/status/1552286486476689410) shows two pictures of musical instruments. Note that the second picture shows both instruments are shown in full. The [resulting image composition](https://mosaic.fxtwitter.com/webp/1552286486476689410/FYrUU4wVUAEIkib/FYrUVU0VsAAOzas) also shows both images in full, as expected. 

However, in the Discord app, the image is cropped horizontally, such 
![image](https://user-images.githubusercontent.com/6588959/181296508-1fa88e92-7188-4e34-b9e4-baeb16c1e829.png)
![image](https://user-images.githubusercontent.com/6588959/181296560-38b09c90-43ca-4a6b-8f0b-72924a816c45.png)

The image dimensions being used by Discord have the wrong aspect ratio. The original image is 2106x590, which is an aspect ratio of roughly 7:2. The preview used by Discord is 1605x904, as it's forced to a 16:9 aspect ratio. It also zooms the image vertically, which is unexpected.

**Comment by Antonio32A** [comment]
This isn't an issue with mosaic really, since it produces a perfectly valid image. The worker is assuming the width and height ([here](https://github.com/dangeredwolf/FixTweet/blob/main/src/mosaic.ts#L48)) resulting in Discord resizing it. I've already created a PR (https://github.com/FixTweet/mosaic/pull/3) which adds a /size endpoint so the worker can fetch it from there.

**Comment by Antonio32A** [comment]
Fixed in https://github.com/dangeredwolf/FixTweet/pull/12.
